config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cities do
    collection do
      post :import
      delete :clear
    end
  end

  root "cities#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: cities
#
#  id          :integer          not null, primary key
#  city        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

require "csv"

class City < ApplicationRecord
  validates :city, presence: true

  # This skips validation.
  def self.import_csv(file_path)
    imported_cities = City::ImportCsv.new.import(file_path)

    transaction do
      imported_cities.each do |imported_city|
        record = City.find_or_create_by!(city: imported_city[:city])
        record.update!(description: imported_city[:description])
      end
    end

    imported_cities.count
  rescue StandardError => exception
    Rails.env.test? ? raise(exception) : logger.error(exception)
    false
  end

  def self.to_csv
    attribute_names = %w[city description]
    CSV.generate(headers: true) do |csv|
      # Add attribute names to the first row.
      csv << attribute_names

      # Add attribute values to the following rows for each record.
      # NOTE: Previously defined scopes will still be effective here.
      all.find_each do |city|
        csv << city.attributes.values_at(*attribute_names)

        # Getting attribute values
        #   csv << user.attributes.values_at(*attribute_names)    # Pattern A: attributes that exist in database
        #   csv << attribute_names.map { |attr| user.send(attr) } # Pattern B: attributes that exist in database + virtual attributes
      end
    end
  end
end

app/models/city/import_csv.rb
# frozen_string_literal: true

require "csv"

# Responsible for importing a csv file and converting it into array of hashes.
# First col: city
# Second col: description
class City::ImportCsv
  def import(file_path = Rails.root.join("db", "cities.csv"))
    options = {
      headers: true,
      encoding: "iso-8859-1:utf-8",
      header_converters: ->(f) { f.strip.downcase.parameterize(separator: "_") },
      converters: ->(f) { f ? f.strip : nil }
    }

    imported_cities = []
    CSV.foreach(file_path, options) do |row|
      imported_cities << row.to_hash.symbolize_keys
    end
    imported_cities
  rescue StandardError => exception
    Rails.env.test? ? raise(exception) : logger.error(exception)
    nil
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
# frozen_string_literal: true

class CitiesController < ApplicationController
  before_action :set_city, only: %i[show edit update destroy]

  # DELETE /cities/clear
  def clear
    count = City.delete_all
    respond_to do |format|
      format.html { redirect_to cities_url, notice: "#{count} cities were successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # POST /cities/import
  def import
    if params[:file].blank?
      flash.now[:danger] = "Please select a csv file"
      @cities = City.all.order(:city)
      render(:index) && return
    end

    count = City.import_csv(params[:file].path)
    if count.present?
      flash[:success] = "#{count} cities were successfully uploaded"
      redirect_to cities_url
    elsif
      flash.now[:danger] = "Couldn't upload the file"
      @cities = City.all.order(:city)
      render :index
    end
  end

  # GET /cities
  # GET /cities.json
  # GET /cities.csv
  def index
    @cities = City.all.order(:city)

    respond_to do |format|
      format.html {}
      format.json {}
      format.csv { send_data @cities.to_csv, filename: "cities-#{Date.today}.csv" }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show; end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit; end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to cities_url, notice: "#{@city.city} was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to cities_url, notice: "#{@city.city} was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: "#{@city.city} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = City.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def city_params
    params.require(:city).permit(:city, :description)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/cities/_form.html.slim
= simple_form_for(@city) do |f|
  = f.error_notification

  .form-inputs
    = f.input :city
    = f.input :description, input_html: { style: "min-height: 400px;" }

  .form-actions
    = f.button :submit, class: "btn btn-primary", style: "float: right"

app/views/cities/edit.html.slim
h1 Editing city

== render 'form'

= link_to 'Back', cities_path

app/views/cities/index.html.slim
h1
  | Listing cities
  .d-flex.justify-content-end
    .btn-group
      = link_to fa_icon("plus"), new_city_path,
        class: "btn btn-primary btn-sm", title: 'Create New City', style: "min-width: 100px;"
      = link_to fa_icon("trash-o"), clear_cities_path, data: { confirm: 'Are you sure?' }, method: :delete,
        class: "btn btn-danger btn-sm", title: 'Delete all records', style: "min-width: 40px;"
      = link_to fa_icon("download"), cities_path(format: :csv),
        class: "btn btn-primary btn-sm", title: "Download CSV file", style: "min-width: 100px;"

.my-3

ul.list-group
  = form_tag import_cities_path, multipart: true do
    .d-flex.justify-content-end
      = file_field_tag :file
      = button_tag type: "submit", class: "btn btn-primary btn-sm", title: "Import CSV file", style: "min-width: 100px;" do
        = fa_icon("upload")

.m-3

#city-list
  input.search.form-control [placeholder="Search by city name"]
  .m-2
  ul.list-group.list
    - @cities.each do |city|
      li.list-group
        li.list-group-item.list-group-item-action.flex-column.align-items-start
          .d-flex.w-100.justify-content-between
            h4.city = link_to city.city, edit_city_path(city)
            = link_to fa_icon("trash-o"), city, data: { confirm: 'Are you sure?' }, method: :delete
          p.mb-1.description
            = city.description

javascript:
  window.App.initCityList()

app/views/cities/new.html.slim
h1 New city

== render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.slim
h1= @city.city
p= @city.description

= link_to 'Edit', edit_city_path(@city)
'  |
= link_to 'Back', cities_path

app/views/layouts/_flash.html.slim
/ This is to render a Bootstrap 3 alert according to the specified alert type.
/ - Devise:    notice, alert
/ - Bootstrap: success, info, warning, danger
- flash.each do |type, message|
  - type = :success if notice
  - type = :danger  if alert
  div [class="alert alert-#{type} flash_message"]
    .container
      .message= message
    .clearfix

app/views/layouts/_top_nav.html.slim
nav.navbar.navbar.navbar-inverse [style="background-color: #333;"]
  .container
    a.navbar-brand [href="#{root_path}" style="color: #ddd"] MN
    .d-flex.flex-row
      = link_to "Home", root_path, class: "nav-link"
      = link_to "Cities", cities_path, class: "nav-link"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta [content="text/html" charset="UTF-8", http-equiv="Content-Type"]
    meta [name="viewport" content="width=device-width, initial-scale=1.0"]
    = csrf_meta_tags

    title CSV Import App

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    / = stylesheet_pack_tag 'application'
    / = javascript_pack_tag 'application'

    /[if lt IE 9]
      script [src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"]
  body
    = render "layouts/top_nav"

    #flash
      = render "layouts/flash"

    .container [style="padding-top: 1rem; padding-bottom: 1rem; min-height: 80vh;"]
      main= yield

    .container
      = debug(params) if Rails.env.development?

app/views/pages/index.html.slim
h1 Pages#index
p Find me in app/views/pages/index.html.slim

= link_to "all cities", cities_path